name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - aot
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - aot

jobs:
  # build_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: windows-latest
  #   name: Build Job
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: '6.0.x'
  #         include-prerelease: true
  #     - run: |
  #         cd Client
  #         dotnet --version
  #         dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
  #         dotnet publish -c Release -o out
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: out
  #         path: Client/out

  deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    # needs: build_job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
    #   - uses: actions/download-artifact@v2
    #     with:
    #       name: out
    #       path: out
    #   - run: |
    #       ls -la
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SKY_00ADD8710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Client" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "wwwroot"
          # skip_app_build: true
        env:
          PRE_BUILD_COMMAND: dotnet workload install microsoft-net-sdk-blazorwebassembly-aot && curl -LO https://oryx-cdn.microsoft.io/python/python-3.8.6.tar.gz && mkdir pythonbin && tar xzf python-3.8.6.tar.gz -C pythonbin && echo $PATH && ln -s pythonbin/bin/python3.8 /usr/local/bin/python && which python && /usr/local/bin/python --version
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SKY_00ADD8710 }}
          action: "close"
